### ISSUE TITLE
ID selector return Array by design?

### ISSUE THREAD

**Issue by aarondzl** [madrobby/zepto#1096]
my first time to use zepto,I find an issue
ID selector is return an array,Is this design since the beginning？

codes in zepto.qsa, like this:

found = element.getElementById(nameOnly)) ? [found] : []

**Comment by mislav** [comment]
Yes, that is by design. Zepto is modeled after jQuery, and typically used like so:

```js
var collection = $("#myselector")
collection.length  //=> 1
```

That is, no matter what the CSS selector is, you always operate on arrays.

If you need to select only 1 element by ID in your app, then you don't have to use jQuery or Zepto or anything. You should simply use `document.getElementById("myselector")`.

Is there anything you find broken here?

**Comment by aarondzl** [comment]
thank you
