### ISSUE TITLE
Ajax load not work

### ISSUE THREAD

**Issue by yeeez** [madrobby/zepto#1099]
I get a build use "Zepto Builder" include all modules, and ajax load is not work until i remove "load" from "shortcut methods". is it right?

<pre>
  // shortcut methods for `.bind(event, fn)` for each event type
  ;('focusin focusout focus blur load resize scroll unload click dblclick '+
  'mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave '+
  'change select keydown keypress keyup error').split(' ').forEach(function(event) {
    $.fn[event] = function(callback) {
      return (0 in arguments) ?
        this.bind(event, callback) :
        this.trigger(event)
    }
  })
</pre>

**Comment by mislav** [comment]
Thanks for reporting. It turns out that when you load "event" module *after* "ajax", the Ajax `load()` method gets overriden with the one from `event.js`.

The solution until our next release is to continue removing "load" from the list, as you described, or to ensure that "event" module is loaded before "ajax". With Zepto Builder, the latter solution is probably not possible.
