### ISSUE TITLE
Tap through the point of the event

### ISSUE THREAD

**Issue by xuetian120** [madrobby/zepto#1106]
touch event has many problems.

For example， the Tap event will through the point of the event！

**Comment by madrobby** [comment]
@xuetian120: Hey there! I'm sorry but I don't understand what you mean. Could you give an (simple) example with code and instructions and what you expect to happen and actually happens? Also, is this on all platforms or only on some browsers and devices?

**Comment by benbenye** [comment]
@madrobby :I think @xuetian120 said: 
![image](https://cloud.githubusercontent.com/assets/5770486/9896321/e45fcf5a-5c6c-11e5-8065-479cca62fffb.png)
when the "×" is taped, the 'buttun' which unders the translucent mask layer will be active!

And it will occur on the ios.

**Comment by dioslaska** [comment]
The problem here is that after touchend there are also some mouse events fired by the browser: mousdown, 1 mousemove, mouseup and click. As the dialog is closed on tap (touchend), the subsequent mouse events are fired to the same coordinates, which, in this case will be the button.

The solution to this problem would be to dismiss the mouse events whenever a tap handled, using event capturing on the document element. The [fastclick](https://github.com/ftlabs/fastclick/blob/master/lib/fastclick.js#L128) library uses a similar tehnique.

**Comment by madrobby** [comment]
Perhaps as a workaround, you could use the CSS `pointer-events` property to prevent events on elements you don't want.

I do agree that this is a somewhat unexpected behavior, and I'll keep a global mouse event discarding technique in mind for a Zepto update, tho.
