### ISSUE TITLE
Problem input field: Iscroll5 and Zepto.js conflict

### ISSUE THREAD

**Issue by TheJson** [madrobby/zepto#1130]
Hello, I'm writing a Cordova app and I'm using zepto.js and iscroll...I have a problem with input field...when i tap on any input field, it opens very well but when I close the input after choosing it has the focus so when I tap in another place the device doesn't remove the focus...in a particular case when I have the input email and close the keybord after writting, I tap on another place for remove the focus and the device opens always the keybord. The problem is conflict between Iscroll5 and zepto.js because I remove the iscroll.js it works...Is there anybody that have my same problem??? How can fix it? Thanks!

**Comment by madrobby** [comment]
Without a working example it's hard for us to debug and help. I'd recommend a site like http://codepen.io to put one up. 

Because of this, and the staleness of this issue, I'm closing it. (Fwiw, this sounds a bit like it might be a problem with iScroll, not Zepto. Have you tried getting help from them? It might also be worth it to post this to Stack Overflow, especially if you have a failing live example that you can point people to.)
