### ISSUE TITLE
:not in selector not supported

### ISSUE THREAD

**Issue by futurist** [madrobby/zepto#1135]
there's not() function in Zepto, but If using :not in selector, it's not valid. Can add this function?

Example: $('div:not(".page")')
There's an error

Can fix it?

**Comment by mislav** [comment]
Sorry, Zepto only supports standard CSS selectors. Support for additional jQuery-specific features can be added with the optional "selector" module, but even that doesn't include support for `:not()`. We won't add support for this because it would require us to write a full-blown CSS selector parser.

You should rewrite your query as `$('div').not('.page')`.
