### ISSUE TITLE
zepto IE 11bug

### ISSUE THREAD

**Issue by lcxfs1991** [madrobby/zepto#1137]
There is an error in IE11 in the following code in Zepto version 1.1.4

['width', 'height'].forEach(function (dimension)

Please check.

First pic says it does not support forEach. And you can visit the link to get more details.

![zepto1](https://cloud.githubusercontent.com/assets/3348398/10154440/d321cd7e-6699-11e5-802c-3720a4612522.png)

![zepto2](https://cloud.githubusercontent.com/assets/3348398/10154442/d5e4d2e0-6699-11e5-9b32-4c48591384d3.png)

**Comment by mislav** [comment]
Thanks for reporting! This is confusing, since IE 11 definitely implements Array.forEach. I am able to use `width()` and `height()` methods in IE 11.

Can you please provide more info?

**Comment by madrobby** [comment]
@lcxfs1991 This happens because Internet Explorer runs in a compatibility mode and emulates an older version of itself that doesn't support `forEach`.

This is not a big; Zepto requires that IE doesn't run in a compatibility mode. In order to fix this, your site must specify to IE that compatibility mode is not wanted. Usually just a HTML5 doctype declaration is enough, but for some sites (which are in IE's internal compatibility database) a meta tag might be needed (see the answer on this StackOverflow question: http://stackoverflow.com/questions/27065659/why-does-foreach-not-work-in-an-iframe-in-ie11)

**Comment by lcxfs1991** [comment]
![ie11](https://cloud.githubusercontent.com/assets/3348398/10183623/5fd4c5bc-6764-11e5-98f6-24b395a5f646.png)

Actually the default mode value is ie7. Please take a look at above picture. If ie7 mode is on, your method will still fail ( I have already used the method you mentioned before).

Best regards,

Lee

**Comment by lcxfs1991** [comment]
默认值 = default value

**Comment by mislav** [comment]
@lcxfs1991 Thanks for clearing that up. I think @madrobby's comment is stil valid. In IE11 it seems that you will only get access to latest JS features by including this tag in your pages:

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

This meta tag is required on sites that want Zepto working in IE. Does your site have that?

**Comment by lcxfs1991** [comment]
Yes I have that in the code. Unfortunately, the browser sets the default mode to ie7.
