### ISSUE TITLE
function 'find' is different from jquery

### ISSUE THREAD

**Issue by 493636333** [madrobby/zepto#1184]
html:
<div class="outer">
    <div></div>
    <div></div>
</div>
jquery:
$('.outer').find('div div').length   // 0
zepto:
$('.outer').find('div div').length   // 2
reason:
function 'querySelectorAll' find element begin with itself,but:
$('.outer').find('.outer').length //0
so if the tier of the selector great than 1,function 'querySelectorAll' find element begin with itself

**Comment by mislav** [comment]
Thanks for reporting. Even though you didn't post sample HTML markup, and somebody unfamiliar with the problem would thus have a hard time following what you are trying to say, we're aware of this specific problem, even though we don't have specific plans to fix this because we don't think it's a big deal (and solving would be technically very challenging). Please follow https://github.com/madrobby/zepto/issues/730
