### ISSUE TITLE
if $('xxx') should cache

### ISSUE THREAD

**Issue by 493636333** [madrobby/zepto#1185]
usually，we use $('xxx') to select element,but we repeat selecting same elements many time.
example:
function show () {
    $('xxx').show();
}
function hide() {
    $('xxx').hide();
}
This brings performance loss，many time we write in this way:
var $xxx = $('xxx');
function show () {
    $xxx.show();
}
function hide() {
    $xxx.hide();
}
but if function nested layers too deep, also brings performance loss.
and AMD or CMD let us can't cache elements.
so if we should cache elements in '$' function,although  element can be removed.
but we can provide an argument to chose if we find element again。
like this: $('xxx',true);
we use selector in many events,so it doesn't matter that we cache elements,because it needs.
so we can use $('xxx') every time and don't have to worry about performance。

**Comment by mislav** [comment]
I understand your problem, but we won't adding a caching feature. First of all, lookups of elements by ID are very fast. It's very unlikely that any app will ever be slowed down by those lookups in particular. Second, if we add a cache, then we would have to add some kind of cache expiration too, which opens a whole new can of worms.

So, because this feature would be complex to implement but provide very little payoff, I'm calling it a nope.
