### ISSUE TITLE
what is the document?

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1213]
for the method `offset`,the documentation of zepto said:

> Get position of the element in the document.

and the document of jquery said:

> Get the current coordinates of the first element, or set the coordinates of every element, in the set of matched elements, relative to the document.

so,what is the `document`?
according to the source code,i think jquery treat it as `document.documentElement`,and zepto treat it as  `document`.
please have a look at the source code:
https://github.com/madrobby/zepto/blob/master/src/zepto.js#L708
https://github.com/jquery/jquery/blob/master/src/offset.js#L112

**Comment by mislav** [comment]
"Document" in this context is the visual rendering of the entire page. If the document width or height exceed the size of viewport (the area of a web browser that displays a page), scrollbars will be in effect. The "position of the element in the document" is a measure of how far is this element from the top left corner of the document, regardless of scroll position.

jQuery's approach to this is almost identical to ours, except that they seem to add `documentElement.clientTop/clientLeft` into account. This is only useful in the case when `<html>` element has a CSS border. Since specifying a border to `<html>` is not common practice, I think our implementation is still fine. But if you think this is something that needs fixing, please send us a pull request!

Do you think our documentation should be improved in some way?
