### ISSUE TITLE
is it a good idea to use the global variable RegExp.$1

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1215]
https://github.com/madrobby/zepto/blob/master/src/zepto.js#L216

```javascript
else if (fragmentRE.test(selector))
        dom = zepto.fragment(selector.trim(), RegExp.$1, context)
```
`RegExp.$1`, it's a global variable.
i have marked a breakpoint at that line above, and then debug it.
when the code run to the next line, i found that `RegExp. $1` equals to  `""`. why?
i think it had been changed by browser extensions, maybe the web and the extensions, they are in the same javascript runtime.
although i believe that in most cases,it will run correctly, but at least in debugging mode, many people will encounter the same problem that has occured on me.
by the way,jquery don't use `RegExp.$1`.

**Comment by madrobby** [comment]
You can break _anything_ while debugging. Because JavaScript is single threaded, using `RegExp.$1` is guaranteed to work correctly. While it's non-standard, it works on all browsers Zepto supports. We'd entertain a pull request that changes this if it doesn't make the code more complex or longer. Closing this issue.

**Comment by zzzgit** [comment]
maybe it's a bug of chromium
i've tested it in IE edge firefox chrome, they all run well
but in chromium 51 and 54, it get a strange behavior

if you are interested in this, just test it in chromium

**Comment by mislav** [comment]
> maybe it's a bug of chromium

I've ran our test suite in Chrome 54 and it passed:

<img width="863" alt="screen shot 2016-08-15 at 9 57 47 am" src="https://cloud.githubusercontent.com/assets/887/17658865/d33fec64-62ce-11e6-8b2e-defa01282f5c.png">

Where do you think a bug is? If `RegExp.$1` value is an empty string when debugging, that can be expected because the internals of the debugger might mess it up.

**Comment by zzzgit** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=638073

i've committed a bug to google,and it has been accepted.
