### ISSUE TITLE
.css('property') returns nothing

### ISSUE THREAD

**Issue by quiggle** [madrobby/zepto#18]
.css('property') returns nothing if you don't actually set the property first with zepto, ex:

$(someobj).css("-webkit-transform", "translate3d(0px,0px,0px)");

If we now do alert($(someobj).css("-webkit-transform"));
We get the propety, but if we set the property in our stylesheet it would return nothing, tested in Chrome and iPhone 3gs

**Comment by baseten** [comment]
I'm getting this issue with v1.2.0 when trying to retrieve padding (at least in Chrome 54). It appears to be because the element's style property is set to an empty string by default. So instead of:

```
element.style[camelize(property)] || getComputedStyle(element, '').getPropertyValue(property)
```

It should perhaps be something along the lines of:

```
var style = element.style[camelize(property)] || '';
return style.length ? style : getComputedStyle(element, '').getPropertyValue(property);
```

**Comment by baseten** [comment]
Actually the code is fine, the problem is because I was trying to retrieve the values using camel case (`paddingTop` not `padding-top`), which fails in the `getPropertyValue` call. Perhaps the documentation should state it only works with hyphenated names or there needs to be an `uncamelize` call before the `getPropertyValue` call
