### ISSUE TITLE
stopPropagation() works wired on event delegation

### ISSUE THREAD

**Issue by chrisyip** [madrobby/zepto#718]
Example: [http://jsbin.com/ugadap/6/edit](http://jsbin.com/ugadap/6/edit)

Problems:

When `A.2` is clicked, `click` events will be fired on two divs, both `A.1` and `A.2` are in `pink`. The `stopPropagation()` doesn't take any effects.

When `A.1` is clicked, `click` event that should only be fired on `A.2` is fired, `A.1` should in `red` not `pink`.

The behavior in box `B` are the correct one: event is stopped correctly, fired on correct element.

**Comment by releasethecow** [comment]
it is because zepto use delegate for the on() function. see as below source code of zepto.js:
line:194
`
  function parse(event) {
    var parts = ('' + event).split('.')
    return {e: parts[0], ns: parts.slice(1).sort().join(' ')}
  }
`
line 1056:
`
$.fn.on = function(event, selector, data, callback, one){
      ...
      add(element, event, callback, data, selector, delegator || autoRemove)
      ...
  }
`
line 932:
`
function add(element, events, fn, data, selector, delegator, capture){
      ...
      var handler   = parse(event)
      ...
}
`
that's why we face the "Wrong" event when we use zepto to register events' callback
