### ISSUE TITLE
IE10 breaks onload

### ISSUE THREAD

**Issue by arxpoetica** [madrobby/zepto#916]
Particularly support for ```Zepto(function($){ ... });```

Just how experimental is "experimental support" for IE10 & 11? On your homepage you state "100% support" for IE10+, but I think the most basic Zepto(function($){ ... }); may in fact be buggy in IE10 on Windows 7. I can't 100% verify this yet—but it's the leading suspicion as I'm chasing down a bug.

Some additional information and a question. Did Zepto 1.1.2 regress? It appears this manual fix makes IE10 work again: https://github.com/madrobby/zepto/issues/822#issuecomment-25484330 (that is, change ```/complete|loaded|interactive/``` to ```/complete/```). I've manually made that change in my version of Zepto.js, but it makes me slightly nervous that I'm losing something with that change.

I'm wondering just what exactly experimental support means here. Do you have something more current I can read about IE10 support in Zepto?

**Comment by madrobby** [comment]
Closing stale issue. Feel free to reopen if this is still an issue.

**Comment by mbeenen** [comment]
This still seems like an issue where the doc ready callback can happen early in IE10.

Simple JSBin demonstrating the issue: jsbin.com/dohajoqeba

May want to look at adopting a workaround like this, instead of the current document.body check, which appears insufficient to ensure the entire body is parsed: https://github.com/jquery/jquery/pull/901
