### ISSUE TITLE
Ajax is not working on Opera mini, Zepto1.0 is fine.

### ISSUE THREAD

**Issue by hkongm** [madrobby/zepto#924]
1.12 & 1.13 $.ajax and $.getJSON is not working on opera mini.
we still have lots of opera users, and cannot upgrade our zepto version.
opera is hard to debug, will this bug fixed?
This url will show the bug.
http://m.autohome.com.cn/110/options.html#pvareaid=101125
chrome is ok.

**Comment by madrobby** [comment]
Hi there! Could you please provide a complete failing. reduced example? You can use a site like https://jsfiddle.net to provide that. Without a failing example that we can immediately investigate we can’t reproduce the problem and can’t find and fix the issue. Thank you! (Because this report is old, I've closed the issue. Feel free to reopen if this is still a problem.)
